connection_string = 'postgres://tealsql:tealsql@localhost/tealsql'
sql_pattern = 'cli_test/**/*.sql'
teal_pattern = '{dir}/{name}_{ext}.tl'

[[helpers_for_tables]]
db = 'tealsql'
schema = 'public'
file = './cli_test/db_mappings.tl'
tables = ['testtable1', "everything"]
