[package]
name = "pgteal"
version = "0.1.0"
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.5", features = ["vendored", "module"] }
tealr = {git="https://github.com/lenscas/tealr",branch="bugfix/missing_typerepresentations" ,features=["derive","mlua"],default-features=false}
sqlx = {version="0.5.5", features=["runtime-async-std-rustls","postgres","tls"], default-features=false}
async-std="*"
futures="0.3.15"
either="1.6.1"