[package]
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"
name = "pgteal"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "main"

[[bin]]
name = "flamegraph"

[features]
lua51 = ["tealr/mlua_lua51"]
lua52 = ["tealr/mlua_lua52"]
lua53 = ["tealr/mlua_lua53"]
lua54 = ["tealr/mlua_lua54"]
vendored = ["tealr/mlua_vendored"]

[dependencies]
either = "1.6.1"
futures = "0.3.15"
mlua = "0.6.4"
parking_lot = "0.11.1"
serde = {version = "1.0.126"}
serde_json = "1.0.64"
shared = {path = "../shared"}
sqlx = {version = "0.5.5", features = ["runtime-tokio-rustls", "postgres", "tls", "uuid", "json"], default-features = false}
tealr = {version = "0.8.0", git = "https://github.com/lenscas/tealr", features = ["derive", "mlua", "mlua_serialize", "mlua_module"], default-features = false}
tokio = {version = "*", features = ["rt"]}
triple_buffer = "5.0.6"
uuid = "0.8.2"
