[package]
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"
name = "pgteal"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "main"

[[bin]]
name = "flamegraph"

[dependencies]
async-std = "*"
either = "1.6.1"
futures = "0.3.15"
mlua = "0.6.4"
parking_lot = "0.11.1"
sqlx = {version = "0.5.5", features = ["runtime-async-std-rustls", "postgres", "tls", "uuid", "json"], default-features = false}
#tealr = {git = "https://github.com/lenscas/tealr", branch = "master", features = ["derive", "mlua", "mlua_vendored", "mlua_lua54", "mlua_module"], default-features = false}
#tealr = {path = "../../tealr/tealr", features = ["derive", "mlua", "mlua_vendored", "mlua_lua54", "mlua_module"], default-features = false}
tealr = {git = "https://github.com/lenscas/tealr", features = ["derive", "mlua", "mlua_vendored", "mlua_lua54", "mlua_serialize", "mlua_module"], default-features = false}
#tealr = {version = "0.7.0", features = ["derive", "mlua", "mlua_vendored", "mlua_lua54", "mlua_module", "mlua_serialize"], default-features = false}
serde = "1.0.126"
serde_json = "1.0.64"
shared = {path = "../shared"}
triple_buffer = "5.0.6"
uuid = "0.8.2"
