[package]
name = "pgteal_cli"
version = "0.1.0"
authors = ["lenscas <lenscas@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx-core= {version= "0.5.5", features=["runtime-tokio-rustls","postgres"]}
tokio={version="1.0.1",features=["macros"]}
clap = "2.33.3"
glob="0.3.0"
Inflector = "0.11.4"