name: Build and Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - chore/update_new_dog_gen
    paths:
      - "**/*.rs"
      - ".github/workflows/update_online_docs.yml"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: "hecrj/setup-rust-action@v1"
        with:
          rust-version: stable
      - name: Add doc gen
        #we do a debug install as those compile faster, and we don't need the runtime speed
        run: cargo install --git https://github.com/lenscas/tealr_doc_gen --debug
      - name: Checkout
        uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: 5.4
      - uses: leafo/gh-actions-luarocks@v4.0.0
      - name: install teal
        run: luarocks install tl
      - name: Build tealsql for doc deploy
        working-directory: ./pgteal
        run: | 
          cargo run --bin main --features lua54,vendored > ../libpgteal.d.tl
          cargo run --bin json --features lua54,vendored > ../libpgteal.json
      - name: Build docs
        working-directory: ./
        #hack as there is no way to set a root folder (yet)
        run: generate_docs --json libpgteal.json --name "libpgteal" --build_folder "pages" --root "tealsql"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages/tealsql